In [5]:
import numpy as np

class Perceptron:
    
    # 퍼셉트론 초기화 및 하이퍼파라미터 조정
    def __init__(self, threshold = 0.0, eta = 0.1, n_iter = 10):
        self.threshold = threshold
        self.eta = eta
        self.n_iter = n_iter
    
    # 퍼셉트론으로 fit시키는 메서드
    def fit(self, X, y):
        self.w = np.zeros(1+X.shape[1]) # 가중치 벡터 초기화
        self.errors = [] # 각 에포크에서 오류 저장 리스트

        for _ in range(self.n_iter): # 에포크 수
            errors = 0
            for xi, target in zip(X, y): # 각 데이터 샘플에 대해
                update = self.eta * (target - self.predict(xi))
                self.w[1:] += update * xi # 가중치 업데이트
                self.w[0] += update # 편향 업데이트
            errors += int(update != 0.0) # 업데이트가 발생했으면 오류로 간주
        self.errors.append(errors)  # 에포크별 오류 수 저장
        print(self.w) # 학습된 가중치 출력

        return self
    
    # 입력 데이터 X에 대한 선형 결합 결과를 계산
    def net_input(self, X):
        return np.dot(X, self.w[1:]) + self.w[0]
    
    # net_input(X)이 threshold를 넘으면 1, 그렇지 않으면 -1을 반환하여 이진 분류 수행
    def predict(self, X):
        return np.where(self.net_input(X) > self.threshold, 1, -1)
    
p = Perceptron()
p.fit(np.array([[0,0],[0,1],[1,0],[1,1]]), np.array([-1,-1,-1,1]))
print(p.errors) # 가중치 벡터 변화 10개와 에포크별 오분류된 데이터 수 출력

[0.2 0.2 0.2]
[0.  0.4 0.2]
[-0.2  0.4  0.2]
[-0.2  0.4  0.4]
[-0.4  0.4  0.2]
[-0.4  0.4  0.2]
[-0.4  0.4  0.2]
[-0.4  0.4  0.2]
[-0.4  0.4  0.2]
[-0.4  0.4  0.2]
[1, 3, 3, 2, 1, 0, 0, 0, 0, 0]
